name: Continuous Integration

on:
    push:
        branches: ['main', 'dev']
    pull_request:
        branches: ['main', 'dev']

jobs:
    web:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 # Bring your code into the virtual environment

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm ci

            - name: Lint code
              working-directory: .
              run: npm run lint:fix

            - name: Run Frontend tests
              working-directory: ./web
              run: npm run test

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            
            - name: Run Playwright tests
              working-directory: ./web
              run: npm run test:e2e
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30

            - name: Build Frontend
              working-directory: ./web
              run: npm run build

            - name: Upload Frontend Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: web-build
                  path: ./web/dist

            - name: Run Backend tests
              working-directory: ./api
              run: npm run test

            - name: Run Backend E2E tests
              working-directory: ./api
              run: npm run test:e2e

            - name: Build Backend
              working-directory: ./api
              run: npm run build

            - name: Upload Backend Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: api-build
                  path: ./api/dist



